class_name Pedia
## In-game encyclopedia. Every article ends with the commands that make the
## concept real in this game. Keep articles short and honest.

const DIALECT_EXAMPLES := {
	"Switches & MAC learning": {
		"device_type": "switch",
		"ros": ["ping something", "/interface bridge host print"],
		"eos": ["ping something", "show mac address-table"],
	},
	"VLANs": {
		"device_type": "switch",
		"ros": ["/interface bridge vlan add vlan-ids=10", "/interface set ether2 pvid=10"],
		"eos": ["vlan 10", "interface Ethernet2", "switchport access vlan 10"],
	},
	"Trunks": {
		"device_type": "switch",
		"ros": ["/interface set ether5 mode=trunk", "/interface bridge port print"],
		"eos": ["interface Ethernet8", "switchport mode trunk", "show interfaces trunk"],
	},
	"Spanning tree": {
		"device_type": "switch",
		"ros": ["/interface bridge port print", "/interface set ether4 disabled=yes"],
		"eos": ["show spanning-tree", "interface Ethernet4", "shutdown"],
	},
	"Routing & gateways": {
		"device_type": "router",
		"ros": ["/ip address add address=10.0.0.1/24 interface=ether1", "/ip route print"],
		"eos": ["interface Ethernet1", "ip address 10.0.0.1/24", "show ip route"],
	},
}

static func _example_block(label: String, commands: Array) -> String:
	var lines: Array[String] = [label]
	for command in commands:
		lines.append("  " + String(command))
	return "\n".join(lines)

static func article_text(entry: Array) -> String:
	var title := String(entry[0])
	var body := String(entry[1])
	if not DIALECT_EXAMPLES.has(title):
		return body
	var marker := body.find("\n\nTry:")
	if marker >= 0:
		body = body.left(marker)
	var cfg: Dictionary = DIALECT_EXAMPLES[title]
	var blocks: Array[String] = []
	for dialect in Contracts.dialects_for(String(cfg["device_type"])):
		if dialect == "ros":
			blocks.append(_example_block("Try on PacketTik RouterOS", cfg["ros"]))
		elif dialect == "eos":
			blocks.append(_example_block("Try on OpenRack / Arivista / Junivista EOS", cfg["eos"]))
	return body + "\n\n" + "\n\n".join(blocks)

static func topics() -> Array:
	## a function rather than a constant so the catalogue-driven entries follow
	## the current language
	return [
		["IP addresses & subnets", "An IP address identifies a host; the prefix length (/24) says which part names the NETWORK. Hosts in the same subnet talk directly (via switches); different subnets need a router.\n\n10.0.0.5/24 means: network 10.0.0.0, hosts .1–.254. Two machines in 10.0.0.0/24 reach each other with no router. 10.0.0.5 and 10.1.0.5 do not: no matter how they're cabled.\n\nTry: 'ip addr add 10.0.0.5/24 dev eth0' on a server, then 'ping'."],
		["ARP", "IP needs MAC addresses to actually deliver frames on a LAN. ARP asks 'who has 10.0.0.2?' by broadcast; the owner answers with its MAC; the asker caches it.\n\nWhen ping fails with 'no ARP reply', the target isn't in your broadcast domain: wrong VLAN, wrong subnet, dead cable.\n\nTry: 'ip neigh' (Linux), 'show arp' (EOS), '/ip arp print' (RouterOS), and watch ARP in 'tcpdump'."],
		["Switches & MAC learning", "A switch forwards frames by MAC address. It LEARNS which port each MAC lives on by watching source addresses; unknown or broadcast destinations are flooded everywhere in the VLAN.\n\nTry: ping something, then 'show mac address-table' (EOS) or '/interface bridge host print' (RouterOS): the table filled itself."],
	[Loc.t("pedia.vlans.title"), Loc.t("pedia.vlans.body") + "\n\nTry: 'vlan 10' + 'switchport access vlan 10' (EOS) or '/interface bridge vlan add vlan-ids=10' + '/interface set ether2 pvid=10' (RouterOS). The isolation is real: ping across VLANs and watch it die."],
		["Trunks", "A trunk port carries MANY VLANs between switches by tagging each frame with its VLAN id. Both ends must be trunks; you can prune which VLANs are allowed.\n\nTry: 'switchport mode trunk', then 'switchport trunk allowed vlan 10,20'. Prune a VLAN off the trunk and watch that VLAN split in half."],
		["Spanning tree", "Two links between switches = a loop = broadcasts circulating forever. STP elects a root switch, keeps one loop-free tree, and BLOCKS the spare links: until a live link dies, when a blocked one takes over.\n\nTry: cable two switches twice, then 'show spanning-tree'. Disable the forwarding link: pings survive over the ex-blocked one."],
		["Routing & gateways", "Routers connect subnets. A host sends off-subnet traffic to its DEFAULT GATEWAY; the router looks up the destination in its routing table and forwards, decrementing TTL.\n\nTry: 'ip route add default via 10.0.0.1' on a server; 'ip address 10.0.0.1/24' on a router leg; 'traceroute' shows every router hop."],
		["OSPF", "Static routes don't scale: every new subnet means touching every router. OSPF lets routers exchange what they know: enable it, say which networks participate, and shortest paths appear everywhere.\n\nTry: 'router ospf' + 'network 10.20.0.0/16 area 0' (EOS) or '/routing ospf network add prefix=…' (RouterOS); 'show ip ospf neighbor'; look for O routes in 'show ip route'."],
		["BGP & the internet", "The internet is networks (autonomous systems) exchanging routes via BGP. You buy transit from an upstream, peer with them, learn a default route: and ANNOUNCE your prefixes so the world can answer.\n\nTry: buy an ISP Handoff, 'router bgp 65001', 'neighbor 100.64.0.1 remote-as 64500', 'network <prefix>'. 'show ip bgp summary' shows the session."],
		["NAT", "Private addresses (10.x, 192.168.x) don't belong on the internet. NAT rewrites private sources to the router's public address on the way out and un-rewrites replies. Outbound works; unsolicited inbound doesn't: that needs a real announced address.\n\nTry: 'ip nat outside' on the uplink-facing interface (EOS) or '/ip firewall nat add chain=srcnat action=masquerade out-interface=ether1'."],
		["DHCP", "Nobody types IP addresses at scale. A DHCP client broadcasts DISCOVER; a server in the same broadcast domain leases it an address, gateway and DNS. Broadcast domain matters: DHCP doesn't cross routers (or VLANs).\n\nTry: 'dhcpd eth0 10.2.0.10 10.2.0.99 24 10.2.0.1 10.2.0.5' on one server, 'dhclient eth0' on another."],
		["DNS", "Names, not numbers. A resolver asks a DNS server; A records map names to addresses; reverse (PTR) maps addresses back.\n\nTry: 'dns add www.example.hu 10.2.0.10' on a server, 'nameserver <server-ip>' on a client, then 'nslookup www.example.hu': and 'ping' by name."],
		["Firewalls & ACLs", "Segmentation policy: rules matched top-down, first match wins, and every list ends with an invisible 'deny any any': a packet no rule names is dropped, so a list that only denies things blocks everything. End it with 'acl permit any any'. Rules can name a protocol and a port ('acl deny tcp any host 172.16.2.20 eq 22'), and 'established' matches only the answering half of a conversation. Careful: a stateless deny also kills the RETURN traffic of flows you meant to allow. That asymmetric breakage is the classic firewall lesson. Stateful firewalls fix it: they remember flows they forwarded and auto-permit the replies ('firewall stateful' in config mode).\n\nTry: 'acl deny 172.16.1.0/24 172.16.2.20/32' then 'acl permit any any' on a firewall, 'show acl', and ping from both directions."],
		["Wireless", "An access point is not magic, it is a small bridge with a radio on one side. Each SSID it broadcasts maps to a VLAN, its wired uplink is a trunk carrying those VLANs, and a device that associates ends up in the VLAN its network maps to, exactly as if somebody had patched it into that port.\n\nThat is why guest wireless is genuinely separated from staff wireless: not because the radio is different, but because the two SSIDs land in different VLANs and the routing and firewalling between them is the same problem as anywhere else.\n\nTry: 'ssid guest-wifi vlan 30' and 'ssid staff-wifi vlan 31' on an AirTurul AP3, make its uplink a trunk, then 'wifi join guest-wifi' on a host and see where it ends up."],
		["Protected ports and storms", "Two customers in the same VLAN can see each other, which is usually not what either of them bought. Protected ports (the simple form of a private VLAN) fix that without giving every tenant their own subnet: protected ports may talk to the gateway, and to nothing else on the switch.\n\nStorm control is the other half of keeping a shared segment civil. A loop, a broken card or a badly behaved host can flood a VLAN with broadcast; a per-port limit caps how much of that a single port may contribute, and the switch logs when it starts suppressing.\n\nTry: 'switchport protected' on customer ports (leave the gateway port alone), and 'storm-control broadcast <frames>' where you expect trouble."],
		["Rogue servers and spoofed addresses", "A customer machine can answer DHCP just as well as your server can, and whoever answers first owns the client's default gateway. That is a rogue DHCP server, and it is usually somebody's misconfigured home router rather than an attacker.\n\nDHCP snooping fixes it by deciding which ports are allowed to carry a server's answer: the uplink towards your real server is trusted, customer ports are not, and replies from anywhere else are dropped. While it watches, it also records which address was leased to which machine.\n\nThat table then powers dynamic ARP inspection: a machine claiming an address that was leased to somebody else gets its ARP dropped, which stops the classic man-in-the-middle before it starts.\n\nTry: 'ip dhcp snooping' and 'ip arp inspection' on a switch, 'ip dhcp snooping trust' on the uplink, then 'show ip dhcp snooping'."],
		["802.1X: who is allowed on", "Port security asks whether the machine on this port is the one that was here yesterday. 802.1X asks a better question: is this machine allowed on the network at all?\n\nA port with authentication carries nothing until the switch has asked an authentication server about the device, and the server can also answer with the VLAN that device belongs in, so where a machine lands is decided centrally instead of by whoever patched the cable.\n\nOne prerequisite bites in the real world and here too: the switch must be able to reach the server itself, which means the management network has to work before authentication can.\n\nTry: 'radiusd add <mac> [vlan]' on a server, 'radius-server host <ip>' and 'dot1x' on the switch ports, then 'show dot1x'."],
		["Port security", "An access port can be locked to the first device it sees (a sticky MAC). Plug in anything else and the port shuts down, which stops someone unplugging a server to get themselves a free wired connection.\n\nIt is also a famous foot-gun: legitimately moving a server trips the port, and you get a call about a 'dead' switch that is doing exactly what you told it to.\n\nTry: 'switchport port-security' under an access interface, then 'show port-security'."],
		["Management networks", "If customers can reach your switch/router management addresses, you WILL be breached (the event log will tell you). Keep management on its own network: Management ports, separate addressing, firewalled off.\n\nTry: 'interface Management1' + 'ip address' on a switch, cable it to a dedicated mgmt segment, and 'ssh' into it from your ops box."],
		["VRRP", "A gateway that can't die: two routers share one VIRTUAL IP; the highest-priority live member answers it. Clients point at the virtual address and never notice a failover.\n\nTry: 'vrrp 1 ip 10.40.0.1' on two routers ('vrrp 1 priority 120' on the preferred one), 'show vrrp', then kill the master."],
		["Router on a stick", "One router port can serve many VLANs: cable it to a switch TRUNK and split it into 802.1Q subinterfaces, one per VLAN, each with its own gateway address. Frames leave tagged with the subinterface's VLAN id.\n\nIt is the cheap way to do inter-VLAN routing (one port instead of one leg per VLAN), at the cost of all traffic sharing that single link: compare with an L3 switch, which routes at full speed inside the box.\n\nTry: 'interface Ethernet1.60', 'encapsulation dot1q 60', 'ip address 10.90.60.1/24', and repeat for the next VLAN."],
		["L3 switches and SVIs", "A plain switch only moves frames inside a VLAN; crossing VLANs needs a router. An L3 switch (here: the Arivista 7024) can do the routing itself through SVIs: virtual interfaces bound to a VLAN, each with an IP that hosts in that VLAN use as their gateway.\n\nThat collapses a rack of router legs into one box, which is exactly how real campus cores are built.\n\nTry: 'vlan 40', then 'interface Vlan40' and 'ip address 10.80.40.1/24'. Repeat for another VLAN and the switch routes between them."],
		["Anycast", "The same address, announced from more than one place. Routers do not treat that as a conflict, they treat it as a choice: each one sends traffic towards whichever announcement is closest by routing cost, so users are served by the nearest instance without knowing that more than one exists.\n\nFailover is the same mechanism seen from the other side. Take an instance away and its announcement disappears, so every router that preferred it simply picks the next closest, and the service carries on at the same address.\n\nIt needs a routing protocol that has a notion of distance: put the service address on two routers, advertise it into OSPF from both, and look at 'show ip route' on a third to see which one it chose and at what cost."],
		["Spine and leaf fabrics", "Campus networks hang access switches off one big core. Datacenters do not: every leaf uplinks to every spine, no leaf talks to another leaf directly, and traffic is spread across all the uplinks by hashing each flow onto one of the equal-cost paths.\n\nThe payoff is that capacity and resilience come from the same structure. Losing a spine costs you a fraction of your bandwidth instead of half your network, and adding capacity means adding another spine rather than replacing the core.\n\nBuild one with routers as leaves and spines, a small transit subnet on every uplink, and OSPF across the lot; then check 'show ip route' on a leaf and see the same destination twice."],
		["Link aggregation", "Two parallel links between switches and STP idles one of them. Port-channels (LACP) bundle the links into ONE logical pipe: the capacity of all members, failover inside the bundle, and spanning tree sees a single edge so nothing is blocked.\n\nTry: 'channel-group 1' on both member interfaces of BOTH switches (or '/interface bonding add slaves=ether2,ether3'), then 'show port-channel' and 'show spanning-tree'."],
		["Quality of service", "QoS does not create bandwidth. It decides who goes without.\n\nOn a link with no policy, congestion is shared: every customer crossing it degrades together. Turn on priority queueing and the link is allocated instead, strictest service levels first, until the capacity runs out; whoever is left over is the one who suffers. That is exactly why a 99.99 percent contract is worth paying for and exactly why selling too many of them does not work.\n\nTry: 'qos priority-queueing' under an interface (or the QoS switch in the port editor), oversubscribe the link, and watch which customer keeps their service."],
		["Capacity & congestion", "Every port has a speed (PacketTik 1G, Arivista 10G) and a link runs at its slower end. Customer deals carry real load: when the loads crossing a link exceed its capacity, those customers degrade and pay half. The Map draws congested links thick red with load/capacity.\n\nFix it like an engineer: 10G core hardware on hot paths, bundles, or spreading tenants."],
		["Standards and templates", "The tenth switch should not be configured like the first. Build one properly, save it as a template, and stamp it onto every switch that follows: the VLAN database, the port profiles, the security settings and the firewall policy all come across.\n\nWhat does not come across is identity: addresses and hostnames stay with the device, because those are unique per box. That split, policy in the template and identity per device, is the whole idea behind a golden config.\n\nTry: 'copy running-config template access-standard' on a device you like, then 'copy template access-standard running-config' on a new one, or use the Templates button in the device view."],
		["Saving your work", "A device's RUNNING config is what it is doing now; the STARTUP config is what it will come back with after a reboot. They are not the same thing, and the gap between them has ended many careers.\n\nIn this game power blips really do reboot gear: anything you never saved comes back blank.\n\nTry: 'write memory' (or 'copy running-config startup-config'), 'show startup-config' to see whether you have unsaved drift, and 'reload' to find out the hard way. PacketTik: '/system backup save' and '/system backup load'."],
		["IPv6", "The internet ran out of 32-bit addresses. IPv6 uses 128 bits, written as eight hex groups with a run of zeros collapsed to '::', and hands out /64s to LANs the way IPv4 hands out /24s.\n\nThe shape of the job does not change: you address interfaces, you route between prefixes, and a host still needs a gateway. What changes is the neighbour lookup: ARP is replaced by Neighbor Discovery, which you can watch in a capture.\n\nTry: 'ip -6 addr add 2001:db8:1::10/64 dev eth0' and 'ping6' on a server, 'ipv6 address 2001:db8:1::1/64' under a router interface, then 'show ipv6 neighbors' and 'show ipv6 interface brief'. Both families run side by side on the same wire."],
		["Logging and clocks", "A device remembers the last few things that happened to it, and forgets everything else. That is fine until you are correlating an outage across five devices at three in the morning.\n\nRun a collector ('syslogd' on a server), point devices at it ('logging host <ip>' on network gear, 'logging <ip>' on a host), and the record survives in one place. Then make the timestamps trustworthy: without a clock source, device clocks drift apart, and two logs of the same event will not line up. 'ntp server <ip>' fixes that, and 'show clock' tells you whether the device is disciplined or guessing.\n\nLogs that cannot reach the collector are simply lost, which is its own lesson about where you put the management network."],
		["Troubleshooting method", "Debug networks bottom-up, halving the problem each step.\n\n1. PHYSICAL: is the port up and cabled? ('interface print', 'show interfaces', lldp, the Map)\n2. L2: same VLAN? MAC learned? ('show vlan', 'show mac address-table', trunk allowed lists)\n3. ADDRESSING: right subnet and mask? ('ip addr': 10.0.0.5/24 and 10.1.0.5/24 will never ARP each other)\n4. GATEWAY: can you ping your default gateway? If yes, the LAN is fine and the problem is routing.\n5. ROUTING: 'show ip route' both directions. Traffic must know the way BACK too.\n6. POLICY: firewalls drop silently; 'show acl' and remember stateless kills return traffic.\n\n'tcpdump' at each hop shows where packets die. The answer is always at the layer where the evidence stops."],
		["Telling people", "An outage costs you twice: once in service and once in trust. The second cost is the one you control.\n\nPost an honest update while the thing is broken and customers forgive far more of it than if they discover the outage themselves and then discover you said nothing. In this game that is a real number: silence during an outage costs noticeably more reputation than a status update does.\n\nSpares are the other half of a short outage. A shelf unit costs three quarters of a new device and turns a failure into a swap, and if the failed device had its configuration saved, the replacement comes up with it. If it did not, you are configuring a switch from memory while a customer waits."],
		["Incident response", "Something broke at 3am. Resist the urge to change things: DIAGNOSE first.\n\nWhat changed? (event log, FIELD faults). What still works? (halve the search space). Follow the troubleshooting method layer by layer; fix ONE thing, re-test, repeat.\n\nPractice safely: the system menu offers incident drills: a disposable network with hidden faults, real tools, a debrief if you give up, and a bonus if you fix it. Your own datacenter is untouched."],
		["WireGuard", "A newer kind of tunnel, and a different mental model. There is no negotiated session between two endpoints: each side has a key, lists the peers it will talk to by their public key, and gives every peer a set of allowed IPs.\n\nThat list does two jobs at once, which is the thing worth understanding. It is the routing decision, because traffic is sent to the peer whose allowed IPs cover the destination, and it is the access control, because traffic arriving from a peer is dropped unless the source is inside that same list. Anything outside it is simply not carried.\n\nOne practical consequence bites everyone once: the peer's own tunnel address has to be in its allowed IPs too, or the tunnel's own subnet cannot be routed.\n\nTry: 'interface wg0', give it a small address, then 'wireguard peer <their-key> endpoint <their-public-ip> allowed 10.0.0.0/24,10.99.0.2/32' on both sides, and 'show wireguard' to see the handshake. On a server: 'wg up 0', 'wg addr 0 ...', 'wg peer 0 <key> <endpoint> <allowed>', 'wg show'."],
		["Tunnels", "A leased circuit is a wire you rent. A tunnel is a wire you pretend to have: two routers agree on endpoints, and traffic between them is carried over whatever path already exists, usually the internet.\n\nIt is cheaper, because you are not paying a carrier for a dedicated line, and it is only as good as the path underneath. If the underlay breaks, the tunnel goes down with it, which 'show tunnels' will tell you plainly.\n\nTry: 'interface Tunnel1', 'tunnel source <your public ip>', 'tunnel destination <their public ip>', give it a small point-to-point subnet, and route the far side's networks through it."],
		["Distance and latency", "Light in fibre travels about two hundred kilometres every millisecond, and carriers never lay the straight line, so a link between two cities costs real time that no amount of bandwidth removes.\n\nInside a building latency is negligible. Between sites it is not, and it shows up in ping and traceroute as the actual number. That is why where you put a service matters for customers who care about response time, and why bandwidth and latency are two different problems: adding capacity to a slow path does not make it fast.\n\nSite cities are shown in the Business tab, and circuit orders quote the distance."],
		["LAN, WAN and circuits", "Inside a building you run your own cables and bandwidth is nearly free. Between buildings you do not: you lease a circuit from a carrier, pay for it every month, and live with the bandwidth grade you bought.\n\nIn this game a cable between two sites only connects if a circuit exists between them, the circuit's grade becomes that link's capacity (so customer traffic can congest it), and the fee shows up in your cycle costs. Cancel the circuit and every cable riding it goes down, which is exactly what happens when an invoice goes unpaid.\n\nOrder circuits from the Business screen once you operate more than one site."],
		["VRFs: many tables, one router", "Two customers both want 10.0.0.0/24, and they are both entitled to it. A router normally has one routing table, so the second one loses.\n\nA VRF is a separate table inside the same device. Put each customer's interfaces in their own VRF and their addresses stop colliding: the router reaches 10.0.0.50 in one table and a completely different 10.0.0.50 in the other, and neither can see the other. Neighbour caches are per table too, for the same reason.\n\nThis is the honest alternative to re-addressing an acquisition: instead of renumbering somebody's network, you keep it whole and give it its own table.\n\nTry: 'ip vrf alfa', then 'ip vrf forwarding alfa' under an interface, then address it. 'show ip vrf' lists the tables, and static routes take an optional 'vrf <name>'."],
		["Virtual machines and live migration", "A server is no longer one machine. It hosts several, each with its own MAC and address, bridged onto the host's uplink.\n\nThe interesting part is moving one. A live migration keeps the machine's addresses and puts it on a different host, so from the network's point of view the same MAC and IP suddenly appear on a different port. That works if both hosts sit in the same broadcast domain, and it does not if they do not: the machine lands with an address that means nothing where it now lives.\n\nThat single requirement is why datacenter networks are built the way they are, stretching layer 2 further than anyone really wants to, and why overlays like VXLAN exist to do it without a flat network.\n\nTry: 'vm create web01', 'vm addr web01 10.160.0.20/24', then 'vm migrate web01 <other host>' with the two hosts in the same VLAN and again with them apart."],
		["Mergers and migrations", "Buying a competitor hands you their racks exactly as they ran them: their VLAN numbering, their addressing, their cabling, and their customers who expect no interruption.\n\nThe integration is the real work. Their subnet very likely collides with yours (everyone loves 10.0.0.0/24), their VLAN ids mean something different on their switches, and their gear is not cabled to your network at all. You must connect the two estates, resolve the address conflicts by re-addressing one side, keep the inherited services reachable throughout, and save the configs on kit you have never touched before.\n\nA small shop's rack simply moves into your room. A company with its own server room or datacenter floor is bought together with the building: it becomes another site you operate, and you switch floors from the HUD. Linking two sites is a WAN problem, not a patch cable.\n\nThis is what real acquisitions look like from the network team's desk."],
		["Under attack", "Sooner or later somebody floods one of your customers. The traffic arrives over your transit and fills the same links your other customers use, so one victim can take out everyone.\n\nYou have three answers and all of them cost something. Pay an upstream to scrub the traffic before it reaches you: effective, and a recurring bill. Blackhole the victim's address with a discard route ('ip route 203.0.113.5/32 null0'): the flood stops instantly, the network recovers, and that one customer is definitively offline, which is a decision to make with them, not for them. Or ride it out and eat the congestion.\n\nThe uncomfortable truth of the blackhole is the lesson: you finish the attacker's job for them, deliberately, to save everyone else."],
		["Pricing against rivals", "Customers do not only compare your price against their budget, they compare it against other suppliers. Quote above what a competitor would charge and they take the job, and the event log tells you the price you lost to.\n\nEvery loss teaches you something: after your first, offer cards show an estimated band for what rivals would charge, and it tightens as you see more bids and as your reputation grows. Large operators ignore small jobs, so a new shop always has work available at a decent margin, and a strong reputation makes existing customers harder to poach.\n\nCharge under the market and you win the job but earn less; charge over it and you may not have a job at all."],
		["Load balancing", "One server is one outage waiting to happen. A load balancer takes a virtual address, keeps a pool of real servers behind it, and hands each new conversation to a healthy member: the client only ever talks to the virtual address, and the answer comes back wearing it.\n\nThe pool is kept honest by health checks. A member that stops answering is taken out of rotation and the service carries on with the rest; when every member is down the virtual address stops answering too, which is the honest failure rather than a silent one.\n\nTry: buy an Equipoise LB10, then 'virtual-server 10.190.0.100 members 10.190.0.11,10.190.0.12' and watch 'show virtual-server' as you switch a server off."],
		["Contracts end", "A customer contract runs for a term and then comes up for renewal, and what they offer you at that point is a verdict on the service they got. Keep them above ninety-five percent with a decent reputation and they will pay more than before. Let them sit at eighty and they will ask for a discount, and you can either take it or let them go.\n\nNothing is billed while the customer is deciding, so a renewal is not something to leave sitting in the Jobs tab.\n\nIt is the same lesson as service levels seen over a longer horizon: uptime is not a technical statistic, it is your price."],
		["Service levels", "Customers do not only buy connectivity, they buy a promise about it. A best-effort contract pays the least and forgives outages. A 99.9 percent contract pays about half again as much, and a 99.99 percent one roughly double, but both charge money back when you miss the number.\n\nUptime is measured over the life of the contract, so an early outage haunts you for a long time and redundancy stops being a luxury: VRRP gateways, bundled links, a second circuit and spare hardware all pay for themselves in penalties not incurred.\n\nThe Jobs tab shows each contract's tier and its running uptime."],
		["Kit gets old", "Hardware does not fail randomly, it fails increasingly. A switch bought two hundred cycles ago is not the switch you installed, and past a certain age the chance of it dying climbs every cycle.\n\nThat turns the cheap-versus-enterprise decision into a real one over a long game, and it gives insurance a point: a per-cycle premium that pays towards a replacement converts an unpredictable outage into a predictable cost. Whether that trade is worth it depends on how much of your estate is old and how much a failure costs you in service-level penalties.\n\nThe Ops dashboard shows what you have; the Business tab is where you buy cover and decide how much to spend on marketing to keep the enquiries coming."],
		["The business", "Contracts pay once, then keep paying a service fee every cycle: while the sim verifies they still work. Customers negotiate: they hint at their budget, you quote. Power costs money once you own the room; heat trips gear without cooling; debt compounds; reputation moves budgets. Uptime IS the business."],
		["One stream, many listeners", "A normal switch treats a frame nobody has learned as something to flood everywhere. That is fine for one ARP request and terrible for a video stream: every port carries it, whether anyone wanted it or not.\n\nMulticast fixes the addressing. A group like 239.1.1.1 maps to a link-layer address starting 01:00:5e, and a host that wants the stream says so out loud with a membership report. Switches listen in on those reports (that is what IGMP snooping means) and remember which port asked for which group. After that, the stream goes down exactly those ports.\n\nTry it: turn on `ip igmp snooping` on the switch, run `igmp join 239.1.1.1` on two servers, then `igmp send 239.1.1.1` from a third. Two receive it. The one that never joined never sees it. Turn snooping off and everyone gets a copy."],
		["Two switches, one bundle", "A server with two network cards plugged into the same switch is still one switch away from being offline. Plug the second card into a second switch and you have solved that, but created a new problem: the server now has two paths into the same broadcast domain, which is a loop, and spanning tree will block one of them.\n\nMLAG is the answer the industry settled on. Two switches agree to act as one for the ports that matter: they share a peer link, they share what they learn, and a bundle with one leg on each switch is treated as a single logical port. Traffic that arrives over the peer link is not sent back out a bundle the other switch could already deliver on, which is what stops the duplicates.\n\nThe server side is an ordinary bond: two cables, one address, one MAC.\n\nTry: 'mlag peer <other-switch>' on both switches, 'mlag peer-link' plus a trunk on the link between them, 'mlag 1' on the port each of them gives the server, and 'bond eth0 eth1' on the server. Then pull one leg and keep pinging."],
		["Two feeds, not one", "Power in a real datacenter arrives twice. Two separate feeds, ideally from two separate substations, run to two separate strips in the back of every cabinet, and the whole point is that either one can die without the room noticing.\n\nThat only works if you plug things in properly. A machine with two power supplies takes one cord from each feed and survives either failing, which is most of what you are paying for when you buy the more expensive model. A machine with one supply survives nothing on its own, so the trick is to spread the single-supply gear across both feeds: half on A, half on B. Put all of it on A and a single utility fault takes out everything at once, which is the mistake this models.\n\nA UPS buys time rather than immunity. It carries a dead feed for a few cycles on battery, long enough for the utility to come back or for you to do something about it, and then it is flat.\n\nThe Ops dashboard lists which devices sit on which feed and tells you exactly what one failure would cost you. Each device's power feed is set in its header, next to its status."],
		["Profitable and broke", "Doing the work and getting paid for it are two different events, and the gap between them is where small companies die. Every cycle you deliver, you raise an invoice; the money arrives when the customer's terms say it does, and their terms depend on what kind of organisation they are. A startup pays almost immediately. A public body takes four cycles and does not care that you have a power bill next week.\n\nSome of them are simply late. You can chase an overdue invoice, which gets you paid on the next cycle and costs you a little goodwill, and goodwill is what sets what customers are willing to pay you. Leave one long enough and it is written off, which costs you both the money and some reputation.\n\nThis is why the balance can fall while the business is healthy: look at Receivables in the Business tab before you conclude you are losing money. If cash is tight and the work is genuinely done, the bank is there, and so is the chase button."],
		["Knowing before the customer does", "Nobody discovers an outage by staring at a rack. They discover it because something was polling the equipment and stopped getting answers, and the difference between a good operator and a bad one is usually just how quickly that happened.\n\nSNMP is the oldest and most universal version of that. Each device runs a small read-only agent guarded by a community string, which is effectively a password, and a monitoring station asks it for its interface table: which ports are up, how many frames they have moved. Nothing exotic, and nothing the device would not otherwise know.\n\nWhat makes it a networking exercise rather than a checkbox is that the poll is ordinary traffic. It needs a route, it needs the agent to be running, and it needs the community to match. Getting monitoring working means getting your management network right, which is exactly the thing people leave until last.\n\nTry: 'snmp-server community public' on a switch (RouterOS: '/snmp set enabled=yes community=public'), then 'snmpwalk <its-address> public' from a server. Break the path and watch it fail for the right reason."],
		["Faster trees, and more than one", "The original spanning tree was written when a switch could afford to be careful. When a link failed, the standby port sat listening and then learning for the best part of a minute before it dared forward anything, and the network was simply down for that time. RSTP replaced the waiting with a handshake and made recovery close to immediate, which is why every switch you will meet defaults to it. Set 'spanning-tree mode stp' if you want to feel the old behaviour: the alternate link takes a cycle to come up and your customers notice.\n\nThe second problem is that one tree means one path. Two cables between two switches, and one of them carries nothing at all, which is a strange thing to pay for. MST fixes that by running a separate tree per group of VLANs: map some VLANs to instance 1 and they take the link the other instance is blocking. Both cables carry traffic, and both are still loop-free.\n\nWhich switch ends up root is not luck either. It is the lowest bridge id, which is priority first and address second, and priority is the knob: 'spanning-tree priority 4096' on the switch you actually want at the centre of your network.\n\nTry: 'show spanning-tree' after each change. The per-instance column tells you which VLANs each port is forwarding."],
		["Knowing the far end died", "A router knows one thing for certain: whether its own port is up. That is much less useful than it sounds. If the switch in the middle loses power, or the far router's line card fails, or the fibre is cut somewhere out in the street, your port stays cheerfully up and your routing table keeps pointing at a next hop that is not there. Traffic goes into a hole and nothing reports a fault, because as far as every device is concerned nothing failed.\n\nBFD is a very small protocol that exists only to solve this. Both ends agree to send each other a heartbeat, and when the heartbeats stop the session drops and the routes that depended on it are withdrawn immediately, without waiting for a routing protocol's much slower timers.\n\nThe part worth remembering is that it takes two. A session with BFD configured on one end only detects nothing at all, which is a satisfying thing to discover in a lab and an unpleasant one to discover in production.\n\nTry: 'bfd' on the interface at each end (RouterOS: '/interface set ether2 bfd=yes'), then disable the far end and watch the route disappear from 'show ip route'. Do it with one end configured first, and watch it not."],
		["Provision for the peak", "Traffic is not a flat line. It collapses overnight, climbs through the morning, peaks somewhere around the middle of the day and tails off in the evening, and over a longer horizon it drifts upward towards the end of the year. The busiest hour is several times the quietest one.\n\nThis matters because a link is sized for its worst moment, not its average. A customer who averages four hundred megabits will hand you well over five hundred at noon, and a gigabit link carrying two such customers is comfortable at three in the morning and congested at midday. Size on the average and you build something that works perfectly every time you look at it and fails every day at lunchtime.\n\nThe figure next to the objective in the top bar is how much of your customers' traffic is flowing right now. When it reads well over a hundred percent, that is the number to plan against. The capacity bars in the Ops dashboard and the moving dots on the cables are showing you the same thing from the other end."],
		["Two circuits, one digger", "Buying a second circuit between two sites feels like buying redundancy. It often is not. If both circuits come from the same carrier, there is a good chance they run down the same duct, through the same exchange, and under the same stretch of road that somebody is going to dig up. When that happens you do not lose one circuit, you lose both, and you paid twice for it.\n\nCarrier diversity is the fix, and it is a procurement decision rather than a technical one: buy the second circuit from a different company. It is usually more expensive and more annoying to arrange, and it is the only version of the second circuit that actually does anything.\n\nThe game will not let you buy two circuits from the same carrier on the same route, and it tells you plainly when a route is carrier diverse. When a carrier has an outage, every circuit you bought from them goes down together, which is the point."],
		["Zones, delegation and the TTL", "No single server knows every name, and none ever did. DNS is a tree of zones, and the useful trick is that a server responsible for example.hu can simply say 'not mine, ask that one' for anything under eu.example.hu. That is a delegation, and a resolver follows the chain down until somebody answers authoritatively. Set one up with 'dns delegate eu.example.hu <address>' on the parent, and the child server never has to be told about the parent at all.\n\nThe TTL is the other half, and it is where the operational pain lives. Every answer comes with a number of cycles the asker is allowed to keep it, and a resolver that has cached a name will keep handing out the old address for that long no matter what you change at the authoritative server. This is why nothing about a DNS change is instant, and why people lower the TTL a day before a migration rather than on the morning of it.\n\nTry: change a record after looking it up and watch the client keep the old address. 'dns cache' shows what it is holding and when it expires; 'dns flush' is the thing you are not supposed to need."],
		["The mismatch that only breaks big packets", "Every port has a maximum frame size, and the standard one has been 1500 bytes since Ethernet ran on coaxial cable. Storage traffic and backups move a great deal more data than a web page does, and they go noticeably faster if you raise that to a jumbo frame of around nine thousand bytes, which is why a storage network is usually configured for it.\n\nThe catch is that every port along the path has to agree. Raise the MTU on the two servers and the switch ports between them and it works beautifully. Leave one port at 1500 and you have built the most frustrating fault in networking: ping works, the interface is up, nothing logs an error, and the application hangs. Small packets fit and are delivered; large ones are silently dropped by the one port that was never changed.\n\nThe only reliable way to find it is to send a large packet on purpose. 'ping -s 9000 <address>' (Arista-style: 'ping <address> size 9000') tells you which device and which port swallowed it.\n\nSet the MTU in the port editor, or with 'mtu 9216' on the interface."],
		["Two upstreams, and who decides", "One transit provider is a single point of failure with a monthly invoice. Two is resilience, and the moment you have two you have to answer a question that did not exist before: which one does the traffic actually use?\n\nOutbound is yours to decide, and local preference is the lever. It is the first thing BGP looks at, before path length or anything else, and the highest value wins. Set 'neighbor <ip> local-preference 200' on the upstream you would rather use and everything leaves that way, however much shorter the other path looks.\n\nInbound is not yours to decide, which surprises people. The rest of the internet picks how to reach you, and all you can do is make one path look worse. Prepending your own AS onto announcements to one upstream ('neighbor <ip> prepend 3') makes that route look longer, and most of the world will use the other one. It is a request, not an instruction.\n\nPrefix lists are the safety rail on both sides. An inbound list says which prefixes you are willing to accept from an upstream, which is what stops a mistake at their end becoming an outage at yours. An outbound list says exactly which of your prefixes you announce, which is what stops your mistake becoming everyone else's.\n\n'show ip bgp summary' prints the policy on each session."],
		["Somebody else announcing your addresses", "BGP has no built-in notion of who owns what. If another network starts announcing your prefix, routers around the world will believe whichever announcement looks better to them, and a good share of your traffic will simply go to somebody else. Nothing on your side breaks. Every light stays green, every service is up, and your customers cannot reach you.\n\nThe defence has two halves and neither works alone. First you sign your prefix with a ROA, which is a public statement that your AS is the legitimate origin. Second, somebody upstream has to actually check announcements against those statements and drop the ones that do not match. A signed prefix with no validating upstream protects nothing, and a validating upstream cannot help with a prefix you never signed.\n\nTry: 'network <your prefix>' then 'roa <your prefix>' under 'router bgp', and 'neighbor <upstream> rpki' on at least one session. 'show ip bgp summary' tells you whether you are actually covered, and names anyone currently announcing your space."],
		["What transit actually costs", "Nobody sensible bills bandwidth by the average, and nobody bills it by the peak either. The industry settled on the 95th percentile: your usage is sampled repeatedly, the highest five percent of samples are thrown away, and you pay for the highest of what is left.\n\nThat rule has a shape you can plan around. One enormous spike costs you nothing, because it lands in the discarded five percent. Two spikes cost you the full amount, because only one of them gets discarded. So a backup window that runs once is free and the same backup window running every day is expensive, and moving it is worth real money.\n\nPeering is the other half. At an internet exchange you plug into a shared fabric and agree with other networks to swap traffic directly, settlement-free: nobody bills anybody. The port costs a fixed amount every cycle whether you use it or not, so it is a bet. Below a certain volume transit is simply cheaper and the exchange is vanity. Above it, each peering session you establish moves another slice of your traffic off the meter and the port pays for itself several times over. It never moves all of it, which is why nobody stops buying transit.\n\nThe Business tab shows the percentile you are being billed on and what each peering session is saving you."],
		["Hot aisles and cold aisles", "Cooling is not a single number for the room. Cold air comes out of a unit, travels a limited distance, gets pulled through the front of the equipment and comes out of the back much hotter, and the entire discipline is about keeping those two air masses apart.\n\nThat is what a hot aisle and a cold aisle are. Cabinets are arranged in rows facing each other, so every front breathes from the same cold aisle and every back exhausts into the same hot one, and the cooling units take the hot air away from there. Get it wrong, push cabinets together with no aisle between them, and each one is drinking its neighbour's exhaust. The room's total cooling capacity can look perfectly adequate while one row quietly cooks.\n\nSo where you put things matters as much as how much you buy. A cooling unit at the far end of the room is worth much less than one in the row that is actually hot, and a cabinet with cabinets pressed against it on all sides runs hotter than the same equipment standing on its own.\n\nThe Airflow section of the Ops dashboard shows watts produced against watts removed for each cabinet, and a cabinet that is losing that argument glows on the floor. When something trips from heat, it trips there first."],
		["The way in when the way in is broken", "Every remote configuration change carries the same small risk: the change is what disconnects you from the thing you are changing. Remove the wrong address, apply the wrong access list, put a management port in the wrong VLAN, and the device is fine, running, and completely unreachable. On a rack in the next room that costs you a walk. In a datacenter in another city it costs a great deal more.\n\nA console server is the answer, and it is deliberately simple. It has serial cables running to the console ports of everything important and its own separate way in, so it can reach those devices without using the network they are on. When the switch's IP configuration is wrong, its serial port does not care: it was never using IP.\n\nThe habit worth building is to cable the console server first, before you need it, because the moment you need it is the moment you cannot get to it to set it up.\n\nTry: run serial cables from an OutOfBand C8 to your switches, then 'console list' and 'console <device>'. Break a switch's management address on purpose and get back in."],
		["Who is allowed to type, and what they typed", "Once there is more than one device and more than one person, local passwords stop working as an idea. Somebody leaves and you have to visit every switch. Somebody makes a change at three in the morning and there is no way to find out who. The answer is central authentication: the device asks a server whether this person may log in, and the server records what they did.\n\nThe part everyone learns the hard way is the failure mode. If the device points at an authentication server and that server becomes unreachable, the device has no way to admit anybody, and you have locked yourself out of your own equipment using a perfectly correct configuration. The fix is one line and it must be there before you need it: a local fallback, so that when the server is unavailable the device falls back to its own account rather than refusing everyone.\n\nThis is also where the console server earns its place. A lockout caused by an unreachable authentication server is exactly the situation a serial port solves.\n\nTry: 'aaad <secret>' on a server, 'aaa authentication login radius <ip> key <secret>' on a switch, then disable the server and try to log in. Add 'aaa authentication login local' and try again. 'show aaa' tells you in advance which of those two you are about to experience, and 'aaad log' is the record of what was typed."],
		["The outage that was in the diary all along", "An expired certificate is the most avoidable outage there is, and it happens constantly. Nothing breaks. The server is up, the network is fine, every light is green, and every client refuses to connect because the certificate says it stopped being valid at some point last night. There is no fault to find, which is precisely what makes it so confusing the first time.\n\nThere are only two real strategies. Watch the expiry dates and renew them by hand, which works right up until the one person who remembered leaves. Or automate the renewal, pay a small amount for it forever, and stop thinking about it. The second is what the industry settled on, and it is worth understanding why: the failure is not technically difficult, it is a calendar problem, and calendars are what computers are for.\n\nThe Ops dashboard lists anything expiring soon with a renew button. Try: 'cert issue shop.example.hu 6' on a server, let it run out, and watch a customer's service go down while every diagnostic tool tells you everything is fine. Then 'cert auto shop.example.hu on' and stop worrying."],
		["Addresses with nobody handing them out", "IPv4 needs a DHCP server: something that keeps a pool, hands out leases, remembers who has what, and is itself a thing that can break. IPv6 was designed so that most hosts do not need one at all.\n\nA router on the segment advertises the prefix it is using. A host hears the advertisement, takes the first 64 bits of that prefix, and generates the other 64 itself out of its own MAC address: split the six bytes in half, push fffe into the middle, flip one bit, and there is an interface identifier no other machine on that link will have produced. It configures the resulting address and takes the router's address as its default route. No server, no pool, no lease database, nothing keeping state anywhere.\n\nThe part that catches people is that this only works on a /64. Not by convention but by arithmetic: the host identifier is 64 bits, so anything longer leaves no room for it. Advertising a /48 or a /112 quietly configures nobody.\n\nTry: 'ipv6 nd ra' on a router interface with a /64 address, then 'autoconf eth0' on a host and look at what it built."],
		["Typing it once", "The first two switches you configure by hand. The tenth you configure by hand with a growing suspicion that you have forgotten something on one of them, and you are right. Configuration drift is what happens when the same change is applied to twenty devices by a person twenty times: nineteen of them match and one does not, and the one that does not is where the outage comes from six months later.\n\nA playbook is the simplest possible answer and it is not clever. It is the same list of commands you would type, written down once, and then run against every device you name. Nothing about it is magic: it opens the same console session you would open and types the same things, so it can do exactly what you can do and nothing more. If a command would fail when you typed it, it fails in the playbook too, and it says so rather than pretending.\n\nThat honesty is the useful part. Run a playbook of switch commands against a server and it will tell you which lines that device refused, which is how you find out that your idea of 'all my devices' and reality have diverged.\n\nPlaybooks live in the Ops dashboard. Write the commands, name it, and run it on every switch."],
		["Running out of addresses", "There are about four billion IPv4 addresses and they were all allocated years ago. Nobody is making more, so the only way to get any is to buy them from somebody who already has them, and that market only moves in one direction. Every block you buy costs more than the last.\n\nThis is why almost nobody gets their own public address any more. Most customers do not need one: their traffic goes out through shared translation, comes back through the same translation, and nothing about their experience is different. It is only when somebody needs to be reachable from outside, or has an auditor who insists, that an address of their own is actually required.\n\nSo address space becomes something you budget rather than something you have. Every customer who insists on a public address consumes one permanently, and when your allocation runs out you have two options: pay the going rate for another block, or turn the work down. That is the pressure that pushed the industry towards shared translation and eventually towards IPv6, where the arithmetic simply stops being a constraint.\n\nThe Business tab shows how many you hold and how many are spoken for. An offer that needs one says so on its card."],
		["The people are the operation", "Everything in this game that fixes itself is fixed by somebody, and that somebody has a shift, a salary, a mood and somewhere else they could be working.\n\nShifts are the first thing to get right. A network does not stop at six in the evening, and neither do the faults. Everyone you hire covers part of the day, and whatever breaks while nobody is on shift simply waits, which turns a five-minute fix into an outage that lasts until morning. Covering the small hours costs a premium, because it should.\n\nMorale is the second. It falls when there is too much going wrong for too few people, and it falls when somebody notices they are paid less than the market would give them. A miserable, underpaid engineer works at half speed and then hands in their notice, and replacing them costs far more than the raise would have. Watch the number and act before it is a resignation.\n\nTraining is the investment. A course costs money and takes somebody off the floor for a few cycles, which hurts exactly when you can least afford it, and they come back better at the job and rather more inclined to stay.\n\nAnd hiring is a negotiation. Offer somebody their asking price and they accept. Offer a little under and it depends on how much they want to work for you, which is what your reputation buys. Offer far under and they take the other job."],
		["The meter and the tax return", "Two costs behave differently from everything else you pay, and both reward paying attention.\n\nElectricity is not one price. It is dearest in the middle of the day and cheapest in the small hours, which is exactly the opposite of when you want it, because the middle of the day is when your customers are busiest and your equipment is working hardest. You can take that risk on the spot rate and pay less on average, or buy a fixed tariff that costs more per watt and does not care what time it is. Either way the cheapest watt is the one you never draw, which is what an efficiency retrofit buys: a permanent slice off the draw, paid for once.\n\nTax is charged on profit, not on revenue, and the difference is where the equipment comes in. A switch does not cost you its price in the quarter you bought it; it writes itself off gradually over its life, and that write-off is deducted from the profit before the tax is worked out. The catch is that allowances only reduce your bill if somebody actually claims them, and without an accountant on retainer you will claim about half of what you are entitled to. Their fee is usually smaller than the difference.\n\nThe first slice of each quarter's profit is untaxed, so a company barely making rent is left alone."],
		["How the bigger work actually arrives", "Small customers turn up with a requirement and a price in mind, and the whole transaction is a haggle. Larger ones do not work that way at all, and if you only know how to haggle you will never see the larger ones.\n\nIt starts as a lead: a company name and a rumour, with no budget attached because nobody has asked them what they want yet. Qualifying it means going out to see them, which costs an afternoon and sometimes turns up nothing at all. That is not a failure of the process, that is the process: finding out early which prospects are real is most of what a sales pipeline is for.\n\nWhat survives becomes a tender, with written requirements: how much availability they need, roughly how much traffic, whether they insist on their own public address. You answer with a price and a commitment. Commit to less availability than they asked for and your proposal is discarded before anyone looks at the number, which is why reading the requirement matters more than sharpening the pencil.\n\nAnd it is not decided on price alone. Your reputation and the customers willing to vouch for you are worth a real percentage against a cheaper rival, which is the return on every quarter you spent delivering properly."],
		["The reliability counter", "The wall sign counts cycles since the last real customer outage. It is intentionally narrower than the alert count: a failed monitor, a disabled unused port, congestion, or an undelivered new installation does not reset it. An established live customer service becoming unavailable does.\n\nThe counter stays at zero while any customer outage is active and begins moving again when service is restored. BEST remembers the longest completed or current streak, so a reset hurts without erasing what the team achieved. Long quiet runs give staff a little pride; watching a good number fall does the opposite."],
		["The link that stays up and lies", "A cable failure you can see is the easy kind. The other kind keeps the port up, the light on and the counters moving, and quietly loses some of what you send. A contaminated optic drops big frames under load and passes small ones. A connector nobody seated properly comes and goes. A damaged pair carries traffic one way and nothing back, so one end insists the link is fine. An MTU somebody changed and nobody wrote down passes a ping and swallows real traffic.\n\nNone of these turn anything red, which is the point. You find them in the counters: input errors climbing on one side, a receive light drifting down, small pings succeeding while big ones vanish. Then you fix the one thing that is actually wrong: a new optic will not cure an MTU, and reseating will not cure a broken pair.\n\nTry: 'show interfaces counters' and watch InErrors and Rx(dBm), then 'ping -s 1450 <host>' against 'ping <host>'."],
		["Naming what has no IPv6 address", "An IPv6-only client asks for an AAAA record. An IPv4-only service does not have one, and never will. DNS64 is the resolver's answer: when there is no AAAA and there is an A, it synthesizes one by embedding the IPv4 address inside a prefix you nominate, usually 64:ff9b::/96. The client gets an address it can talk to, and never learns it was invented.\n\nIt is only half the transition. Naming a thing does not reach it: something on the path has to translate the packets, which is NAT64. Turn on DNS64 without NAT64 and every connection fails, at a perfectly correct-looking address.\n\nTry: 'dns add legacy.example.hu 10.0.0.9' on a server, then 'dns64 64:ff9b::' and 'nslookup -6 legacy.example.hu'. It will say whether the answer was native, cached or synthesized."],
		["Translating between two internets", "NAT64 is the other half. A router or firewall holds the same prefix DNS64 hands out and an IPv4 address to translate from. An IPv6 packet addressed into that prefix leaves as IPv4, with the embedded destination and the pool as its source, and the answer is translated back using state the translator kept for that exchange.\n\nThe state is the interesting part: it is per-exchange and bounded, so it is a real resource, and it is why native IPv6 traffic should never go near the translator when it does not have to.\n\nTry: 'nat64 prefix 64:ff9b:: pool <your v4 address>' on a router, then 'show nat64' to see what it translated and, when it fails, exactly why."],
		["A segment that does not need a cable", "Two switches, no cable between them, and a tenant who wants to be in one VLAN on both. VXLAN puts the frame inside an IP packet and posts it to the other switch, which unwraps it and puts it back in the same VLAN. Each switch is a VTEP: it has a source address, a mapping from VLAN to VNI, and a list of peers. The network in between routes IP and has no idea it is carrying layer 2.\n\nA VNI that does not match is dropped, which is what keeps two tenants apart when they share the same VLAN number.\n\nTry: 'vxlan source <this switch>', 'vxlan vlan 50 vni 5000', 'vxlan peer <the other switch>' on both, then 'show vxlan'."],
		["Telling the other switches what you have", "Left alone, VXLAN floods to every peer to find anything it has not seen. EVPN is the control plane that stops it: when a switch learns an address behind one of its own ports, it tells the other VTEPs, and withdraws it when it goes away. Unicast then goes straight to the VTEP that has it.\n\nThe advertisements ride the same underlay as the traffic, so a broken underlay means no learning, which is a useful thing to remember when the overlay looks healthy and behaves strangely.\n\nTry: 'vxlan evpn' on both leaves, then 'show vxlan' and watch the remote addresses appear without anybody flooding."],
		["Copper that is not a device", "A patch panel switches nothing. Front port three is wired straight through to rear port three, and that is the whole of it. It exists so a run can be traced, labelled and re-patched without anybody crawling behind a cabinet.\n\nThat means a link through a panel must behave exactly like a direct cable: the same neighbours in LLDP, the same spanning tree, the same everything. What changes is that half a patch is now possible: a lead into a panel port with nothing behind it goes nowhere, and a panel patched round into itself is not a link at all.\n\nTry: cable a server into a panel front port, the matching rear port into a switch, and check 'show lldp neighbors': the switch names the server, not the panel."],
		["The window, and the point of no return", "A change window is not permission to be careless; it is a bounded piece of time with a decision in the middle of it. You say what you are touching, how long you need, and what your backout is. Partway through comes the rollback point: if the work is not finished there, you either revert to exactly what was running or push on knowing you cannot get back inside the window.\n\nOverrunning is what costs: the customers stop being excused, the crew are wrecked the next day, and it goes on the record with or without a backout plan. Freezes exist around the things that cannot move, and overriding one is remembered.\n\nTry: submit a plan on a device with unsaved work, then let the window close without finishing it and read what it says afterwards."],
		["Cutting the branch you are sitting on", "The dangerous part of a change is that it travels over the path you are making it through. Shut the wrong port, change the wrong address, apply the wrong ACL, and the device keeps running your new configuration with no way in. It is not broken, and that is what makes it awkward.\n\nThe recoveries cost what they cost: a serial cable from a console server ignores addressing entirely, a walk to the rack costs a couple of cycles, and the same walk at a remote site is a billed site visit. Real gear also gives you the counter-mechanic: arm a confirmed commit and the change reverts unless you come back and confirm it, which is exactly what saves you.\n\nTry: arm a confirmed commit, shut the port you are managing through, and wait."],
		["Working on a room you are not standing in", "The second building is three hundred kilometres away, and most of what you do to it happens down a wire you are also responsible for. That is the whole difficulty: the tool you would use to fix the network runs over the network.\n\nWhat still works when a floor is unreachable is anything that does not depend on that floor: a console into a device you can still route to, the management port on a switch that is on a different path, the out-of-band console server if you bought one. What does not work is everything you were about to type into the box whose uplink you just shut. Confirmed commits exist for exactly this: the change reverts itself if you do not confirm within the window, which is what saves you when the mistake takes away your way back in.\n\nWhen nothing electronic will do, you buy hands: somebody at that site who will reseat a cable, power cycle a box, or walk over and tell you what the lights say. It is slow, it costs money, and the cheaper the facility the sloppier the answer, which is the trade the game is asking you to make.\n\nIn the game: the device panel says when the kit is on another floor, the console says it in the banner, and remote hands are ordered from the operations panel. The reply arrives cycles later, whatever you have decided in the meantime."],
		["Serving one address from two rooms", "A customer whose board has asked what happens if your building burns down is not asking about your generator. They are asking whether the service exists anywhere else, and the honest answer is either yes or no.\n\nThe build is unglamorous. Two floors. A leased circuit between them, which has to exist before a cable between the buildings is even a cable. Kit at both ends, and the service answering at the same address in each room, so losing one room leaves the address still answered by the other. Everything else, the load balancer, the clever routing, is a refinement on that one idea.\n\nWhat makes it real is testing it. A second room that has never been switched to is a room you are paying rent on, and the failover test exists so you find out on a day you chose.\n\nIn the game: buy a circuit between two sites, run the cable, address the copy in the second room the same as the first, then take one room's kit out of service and see whether the service is still there."],
		["Proving it, on a day you chose", "Redundancy that has never been tested is a belief, not a property. Every operator with a customer who cares gets asked to prove it: schedule a test, take the primary away on purpose, and show the service stayed up.\n\nThe value is in the announcement as much as the outage. Everybody knows it is coming, so the people who were going to find out the hard way find out the easy way instead, and the failure happens at a time when the room is full and nobody is asleep.\n\nThe test is judged on customers, not on configuration. A bundle that is up, a second router that is configured and a circuit that is paid for prove nothing on their own: what counts is whether anybody noticed. A test that fails is worth more than one that passes, because it names the thing you would otherwise have found out about at three in the morning.\n\nIn the game: book a failover test in the facility panel. Your upstream goes away for two cycles at the cycle you picked, and the result says who did not survive it."],
		["Carrying the phone", "Somebody has to be reachable when the room is empty, and pretending otherwise is a decision too, just an unmade one. An on-call rota names that person and pays them a retainer for the inconvenience of not being able to go anywhere. It costs money whether the phone rings or not, which is the point: you are buying a guaranteed answer at three in the morning.\n\nWhen it does ring you have two honest options. Get them in, which costs a call-out fee and costs them a night, or decide it waits until the morning, which costs whatever the fault does in the meantime. The second is a real answer: not everything that breaks at three is worth a person driving in for.\n\nThe bill for the first one lands the next day. Somebody who was up all night is more likely to be the one who pulls the wrong cable, and worse at whatever they were supposed to be keeping on top of. Lean on the same person twice in a week and you have bought two incidents to avoid one.\n\nIn the game: put somebody on call in the company panel, and answer the phone when it rings. Watch who is marked tired the day after."],
		["The cabling debt nobody books", "Every fast install leaves something: a lead of the wrong length, a patched port with no label, a run between cabinets that is in nobody's documentation. Individually none of it matters. Together it is why the next incident takes twice as long, why somebody pulls the wrong cable, and why an auditor stops trusting the rest of what you say.\n\nIt is a real trade rather than a moral one. Doing it properly costs money and time on the way in; doing it fast costs nothing now and everything later, and the bill arrives during an outage.\n\nTry: run a cable the fast way, then look at what the cabinet says about itself in Operations."],
	]
