class_name Pedia
## In-game encyclopedia. Every article ends with the commands that make the
## concept real in this game. Keep articles short and honest.

const TOPICS := [
	["IP addresses & subnets", "An IP address identifies a host; the prefix length (/24) says which part names the NETWORK. Hosts in the same subnet talk directly (via switches); different subnets need a router.\n\n10.0.0.5/24 means: network 10.0.0.0, hosts .1–.254. Two machines in 10.0.0.0/24 reach each other with no router. 10.0.0.5 and 10.1.0.5 do not: no matter how they're cabled.\n\nTry: 'ip addr add 10.0.0.5/24 dev eth0' on a server, then 'ping'."],
	["ARP", "IP needs MAC addresses to actually deliver frames on a LAN. ARP asks 'who has 10.0.0.2?' by broadcast; the owner answers with its MAC; the asker caches it.\n\nWhen ping fails with 'no ARP reply', the target isn't in your broadcast domain: wrong VLAN, wrong subnet, dead cable.\n\nTry: 'ip neigh' (Linux), 'show arp' (EOS), '/ip arp print' (RouterOS), and watch ARP in 'tcpdump'."],
	["Switches & MAC learning", "A switch forwards frames by MAC address. It LEARNS which port each MAC lives on by watching source addresses; unknown or broadcast destinations are flooded everywhere in the VLAN.\n\nTry: ping something, then 'show mac address-table' (EOS) or '/interface bridge host print' (RouterOS): the table filled itself."],
	["VLANs", "One physical switch, many isolated networks. Each access port belongs to one VLAN; frames never cross VLANs without a router. Separate customers = separate VLANs.\n\nTry: 'vlan 10' + 'switchport access vlan 10' (EOS) or '/interface bridge vlan add vlan-ids=10' + '/interface set ether2 pvid=10' (RouterOS). The isolation is real: ping across VLANs and watch it die."],
	["Trunks", "A trunk port carries MANY VLANs between switches by tagging each frame with its VLAN id. Both ends must be trunks; you can prune which VLANs are allowed.\n\nTry: 'switchport mode trunk', then 'switchport trunk allowed vlan 10,20'. Prune a VLAN off the trunk and watch that VLAN split in half."],
	["Spanning tree", "Two links between switches = a loop = broadcasts circulating forever. STP elects a root switch, keeps one loop-free tree, and BLOCKS the spare links: until a live link dies, when a blocked one takes over.\n\nTry: cable two switches twice, then 'show spanning-tree'. Disable the forwarding link: pings survive over the ex-blocked one."],
	["Routing & gateways", "Routers connect subnets. A host sends off-subnet traffic to its DEFAULT GATEWAY; the router looks up the destination in its routing table and forwards, decrementing TTL.\n\nTry: 'ip route add default via 10.0.0.1' on a server; 'ip address 10.0.0.1/24' on a router leg; 'traceroute' shows every router hop."],
	["OSPF", "Static routes don't scale: every new subnet means touching every router. OSPF lets routers exchange what they know: enable it, say which networks participate, and shortest paths appear everywhere.\n\nTry: 'router ospf' + 'network 10.20.0.0/16 area 0' (EOS) or '/routing ospf network add prefix=…' (RouterOS); 'show ip ospf neighbor'; look for O routes in 'show ip route'."],
	["BGP & the internet", "The internet is networks (autonomous systems) exchanging routes via BGP. You buy transit from an upstream, peer with them, learn a default route: and ANNOUNCE your prefixes so the world can answer.\n\nTry: buy an ISP Handoff, 'router bgp 65001', 'neighbor 100.64.0.1 remote-as 64500', 'network <prefix>'. 'show ip bgp summary' shows the session."],
	["NAT", "Private addresses (10.x, 192.168.x) don't belong on the internet. NAT rewrites private sources to the router's public address on the way out and un-rewrites replies. Outbound works; unsolicited inbound doesn't: that needs a real announced address.\n\nTry: 'ip nat outside' on the uplink-facing interface (EOS) or '/ip firewall nat add chain=srcnat action=masquerade out-interface=ether1'."],
	["DHCP", "Nobody types IP addresses at scale. A DHCP client broadcasts DISCOVER; a server in the same broadcast domain leases it an address, gateway and DNS. Broadcast domain matters: DHCP doesn't cross routers (or VLANs).\n\nTry: 'dhcpd eth0 10.2.0.10 10.2.0.99 24 10.2.0.1 10.2.0.5' on one server, 'dhclient eth0' on another."],
	["DNS", "Names, not numbers. A resolver asks a DNS server; A records map names to addresses; reverse (PTR) maps addresses back.\n\nTry: 'dns add www.example.hu 10.2.0.10' on a server, 'nameserver <server-ip>' on a client, then 'nslookup www.example.hu': and 'ping' by name."],
	["Firewalls & ACLs", "Segmentation policy: rules matched top-down, first match wins. Careful: a stateless deny also kills the RETURN traffic of flows you meant to allow. That asymmetric breakage is the classic firewall lesson.\n\nTry: 'acl deny 172.16.1.0/24 172.16.2.20/32' on a firewall, 'show acl', and ping from both directions."],
	["Management networks", "If customers can reach your switch/router management addresses, you WILL be breached (the event log will tell you). Keep management on its own network: Management ports, separate addressing, firewalled off.\n\nTry: 'interface Management1' + 'ip address' on a switch, cable it to a dedicated mgmt segment, and 'ssh' into it from your ops box."],
	["VRRP", "A gateway that can't die: two routers share one VIRTUAL IP; the highest-priority live member answers it. Clients point at the virtual address and never notice a failover.\n\nTry: 'vrrp 1 ip 10.40.0.1' on two routers ('vrrp 1 priority 120' on the preferred one), 'show vrrp', then kill the master."],
	["The business", "Contracts pay once, then keep paying a service fee every cycle: while the sim verifies they still work. Customers negotiate: they hint at their budget, you quote. Power costs money once you own the room; heat trips gear without cooling; debt compounds; reputation moves budgets. Uptime IS the business."],
]
